INSERT INTO contacts
(   id,
    name_prefix,
    first_name,
    middle_name,
    last_name,
    name_suffix,
    nickname,
    company,
    department,
    title,
    phone,
    email,
    date_of_birth,
    website,
    notes,
    label
)
VALUES
(   nextval('contacts_id_seq'),
    'Mr',
    'Dwight',
    NULL,
    'Shrute',
    'III',
    NULL,
    'Dunder Mifflin',
    'Sales',
    'Regional Manager',
    '555-555-5555',
    'd.shrute@dundermifflin.com',
    '1975-01-01',
    NULL,
    NULL,
    NULL
),
(
    nextval('contacts_id_seq'),
    NULL,
    'Jim',
    NULL,
    'Halpert',
    NULL,
    NULL,
    'Dunder Mifflin',
    'Marketing',
    'Sales Representative',
    '111-111-1111',
    'j.halpert@dundermifflin.com',
    NULL,
    NULL,
    NULL,
    NULL
);
